# Generated by Django 4.2.5 on 2023-09-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import presign.base.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_globalsettings_status_textsstore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('NEW', 'Unknown'), ('CIN', 'Checked In'), ('COU', 'Checked Out'), ('LFT', 'Left')], default='NEW', max_length=3)),
                ('base_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', presign.base.fields.I18nCharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.event')),
            ],
        ),
    ]
