repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "22.6.0" # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        exclude: ^.*/migrations/.*$
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.12
    hooks:
      - id: djlint-django
        exclude: "^presign/static/vendored/.*"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.1.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.34.0
          - "@typescript-eslint/eslint-plugin@5.52.0"
          - "@typescript-eslint/parser@5.52.0"
          - eslint-plugin-import@2.27.5
          - eslint-plugin-prettier@4.2.1
          - eslint-plugin-unused-imports@2.0.0
        files: ^.*\.tsx?$ # *.ts and *.tsx
        types: [file]
        args: ["-c", ".eslintrc.json", "--max-warnings", "0"]
  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: tsc --noEmit --target ES2016
        language: node
        files: ^.*\.tsx?$ # *.ts and *.tsx
        pass_filenames: true
