repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.12
    hooks:
      - id: djlint-django
        exclude: "^presign/static/vendored/.*"

  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: tsc --noEmit --target ES2016
        language: node
        files: ^.*\.tsx?$ # *.ts and *.tsx
        pass_filenames: true

      - id: eslint
        name: eslint
        entry: eslint
        language: node
        additional_dependencies:
          - eslint@9.12.0
          - "@eslint/js@9.12.0"
          - "typescript-eslint@8.8.0"
          - eslint-config-prettier@9.1.0
        files: ^.*\.tsx?$ # *.ts and *.tsx
        types: [file]
        args: ["--max-warnings", "0", "--fix"]
