# Generated by Django 4.1.7 on 2023-02-23 17:26

from django.db import migrations

import presign.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_event_email_textsstore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="lock_date",
            field=presign.base.fields.DateTimeLocalModelField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="signup_end",
            field=presign.base.fields.DateTimeLocalModelField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="signup_end_shown",
            field=presign.base.fields.DateTimeLocalModelField(
                blank=True, null=True, verbose_name="Shown Signup End"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="signup_start",
            field=presign.base.fields.DateTimeLocalModelField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="lock_date",
            field=presign.base.fields.DateTimeLocalModelField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="signup_end",
            field=presign.base.fields.DateTimeLocalModelField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="signup_end_shown",
            field=presign.base.fields.DateTimeLocalModelField(
                blank=True, null=True, verbose_name="Shown Signup End"
            ),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="signup_start",
            field=presign.base.fields.DateTimeLocalModelField(blank=True, null=True),
        ),
    ]
