# Generated by Django 4.2.5 on 2023-09-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_event_lock_date_alter_event_signup_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer_Email_TextsStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_email_texts_objects",
                        to="base.organizer",
                    ),
                ),
            ],
        ),
    ]
