# Generated by Django 4.2.5 on 2023-09-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_globalsettings_status_textsstore_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantLogEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_events",
                        to="base.participant",
                    ),
                ),
            ],
        ),
    ]
