# Generated by Django 4.2.5 on 2023-09-30 12:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import presign.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_globalsettings_status_textsstore_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantCustomMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    presign.base.fields.I18nTextField(
                        help_text="This text <strong>will be shown to the participant</strong> on their overview page. You can for example use it for requesting more information."
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.participant",
                    ),
                ),
            ],
        ),
    ]
